In [1]:
# Commento

In [1]:
import pandas as pd
percorso_istat = "../../01_Data/Raw_Data/istat_incidenti_raw.csv"
percorso_situas = "../../01_Data/Raw_Data/Comuni - Dimensione Data Indagine 31-12-2020 Stampa 21062026185720.csv"

In [2]:
#
df_istat = pd.read_csv(percorso_istat, dtype={'REF_AREA': str})
df_situas = pd.read_csv(percorso_situas, sep=';', dtype={'Codice Comune (alfanumerico)': str})

In [3]:
display(df_istat.head(3))

print("\n--------------------------------------------------\n")

display(df_situas.head(3))

,DATAFLOW,FREQ,REF_AREA,DATA_TYPE,RESULT,TIME_PERIOD,OBS_VALUE,OBS_STATUS,NOTE_DS,NOTE_REF_AREA,NOTE_DATA_TYPE,NOTE_RESULT,NOTE_TIME_PERIOD,BASE_PER,UNIT_MEAS,UNIT_MULT
0,IT1:41_983(1.0),A,001001,KILLINJ,F,2001,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IT1:41_983(1.0),A,001001,KILLINJ,F,2002,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IT1:41_983(1.0),A,001001,KILLINJ,F,2003,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--------------------------------------------------

,Codice Ripartizione geografica,Codice Regione,Codice Provincia (Storico),Codice Provincia/Uts,Codice Comune (alfanumerico),Codice Comune (numerico),Comune,Comune (dizione straniera),Sigla automobilistica,Capoluogo di Provincia/Uts,Capoluogo di Regione,Popolazione legale,Anno Censimento,Superficie (Kmq),Anno (Superficie),Popolazione residente,Anno (Popolazione residente)
0,1,1,1,201,001001,1001,Agliè,NaN,TO,0,0,2644,2011,"13,1462",2020,2545,2020
1,1,1,1,201,001002,1002,Airasca,NaN,TO,0,0,3819,2011,"15,7393",2020,3633,2020
2,1,1,1,201,001003,1003,Ala di Stura,NaN,TO,0,0,462,2011,"46,3315",2020,459,2020

In [4]:
df_istat.info()

<class 'pandas.DataFrame'>
RangeIndex: 573552 entries, 0 to 573551
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   DATAFLOW          573552 non-null  str
 1   FREQ              573552 non-null  str
 2   REF_AREA          573552 non-null  str
 3   DATA_TYPE         573552 non-null  str
 4   RESULT            573552 non-null  str
 5   TIME_PERIOD       573552 non-null  int64
 6   OBS_VALUE         573552 non-null  int64
 7   OBS_STATUS        0 non-null       float64
 8   NOTE_DS           0 non-null       float64
 9   NOTE_REF_AREA     0 non-null       float64
 10  NOTE_DATA_TYPE    0 non-null       float64
 11  NOTE_RESULT       0 non-null       float64
 12  NOTE_TIME_PERIOD  0 non-null       float64
 13  BASE_PER          0 non-null       float64
 14  UNIT_MEAS         0 non-null       float64
 15  UNIT_MULT         0 non-null       float64
dtypes: float64(9), int64(2), str(5)
memory usage: 70.0 MB

In [5]:
df_situas.info()

<class 'pandas.DataFrame'>
RangeIndex: 7903 entries, 0 to 7902
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Codice Ripartizione geografica  7903 non-null   int64
 1   Codice Regione                  7903 non-null   int64
 2   Codice Provincia (Storico)      7903 non-null   int64
 3   Codice Provincia/Uts            7903 non-null   int64
 4   Codice Comune (alfanumerico)    7903 non-null   str
 5   Codice Comune (numerico)        7903 non-null   int64
 6   Comune                          7902 non-null   str
 7   Comune (dizione straniera)      124 non-null    str
 8   Sigla automobilistica           7811 non-null   str
 9   Capoluogo di Provincia/Uts      7903 non-null   int64
 10  Capoluogo di Regione            7903 non-null   int64
 11  Popolazione legale              7903 non-null   int64
 12  Anno Censimento                 7903 non-null   int64
 13  Superficie (Kmq)                7903 non-null   str
 14  Anno (Superficie)               7903 non-null   int64
 15  Popolazione residente           7903 non-null   int64
 16  Anno (Popolazione residente)    7903 non-null   int64
dtypes: int64(12), str(5)
memory usage: 1.0 MB

In [6]:
colonne_utili_istat = ['REF_AREA', 'DATA_TYPE', 'RESULT', 'TIME_PERIOD', 'OBS_VALUE']

df_istat_clean = df_istat[colonne_utili_istat]

df_istat_clean = df_istat_clean.rename(columns={
    'REF_AREA': 'Codice_Comune',
    'DATA_TYPE': 'Tipo_Dato',
    'TIME_PERIOD': 'Anno',
    'OBS_VALUE': 'N. incidenti'
})

display(df_istat_clean.head(3))

  Codice_Comune Tipo_Dato RESULT  Anno  N. incidenti
0        001001   KILLINJ      F  2001            10
1        001001   KILLINJ      F  2002            10
2        001001   KILLINJ      F  2003             7

In [7]:
df_situas['Superficie (Kmq)'] = df_situas['Superficie (Kmq)'].str.replace('.', '', regex=False).str.replace(',', '.', regex=False).astype(float)

colonne_utili_situas = [
    'Codice Comune (alfanumerico)', 
    'Comune', 
    'Popolazione residente', 
    'Superficie (Kmq)'
]
df_situas_clean = df_situas[colonne_utili_situas]

df_situas_clean = df_situas_clean.rename(columns={
    'Codice Comune (alfanumerico)': 'Codice_Comune',
    'Comune': 'Nome_Comune',
    'Popolazione residente': 'Popolazione',
    'Superficie (Kmq)': 'Superficie_Kmq'
})

display(df_situas_clean.head(3))

  Codice_Comune   Nome_Comune  Popolazione  Superficie_Kmq
0        001001         Agliè         2545         13.1462
1        001002       Airasca         3633         15.7393
2        001003  Ala di Stura          459         46.3315

In [8]:
df_merged = pd.merge(df_istat_clean, df_situas_clean, on='Codice_Comune', how='inner')
df_merged.shape[1]

8

In [9]:
display(df_merged.head())

,Codice_Comune,Tipo_Dato,RESULT,Anno,N. incidenti,Nome_Comune,Popolazione,Superficie_Kmq
0,001001,KILLINJ,F,2001,10,Agliè,2545,13.1462
1,001001,KILLINJ,F,2002,10,Agliè,2545,13.1462
2,001001,KILLINJ,F,2003,7,Agliè,2545,13.1462
3,001001,KILLINJ,F,2004,13,Agliè,2545,13.1462
4,001001,KILLINJ,F,2005,2,Agliè,2545,13.1462

In [10]:
# controllo
df_situas.info()

<class 'pandas.DataFrame'>
RangeIndex: 7903 entries, 0 to 7902
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Codice Ripartizione geografica  7903 non-null   int64
 1   Codice Regione                  7903 non-null   int64
 2   Codice Provincia (Storico)      7903 non-null   int64
 3   Codice Provincia/Uts            7903 non-null   int64
 4   Codice Comune (alfanumerico)    7903 non-null   str
 5   Codice Comune (numerico)        7903 non-null   int64
 6   Comune                          7902 non-null   str
 7   Comune (dizione straniera)      124 non-null    str
 8   Sigla automobilistica           7811 non-null   str
 9   Capoluogo di Provincia/Uts      7903 non-null   int64
 10  Capoluogo di Regione            7903 non-null   int64
 11  Popolazione legale              7903 non-null   int64
 12  Anno Censimento                 7903 non-null   int64
 13  Superficie (Kmq)                7903 non-null   float64
 14  Anno (Superficie)               7903 non-null   int64
 15  Popolazione residente           7903 non-null   int64
 16  Anno (Popolazione residente)    7903 non-null   int64
dtypes: float64(1), int64(12), str(4)
memory usage: 1.0 MB

In [11]:
# controllo
df_merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 548685 entries, 0 to 548684
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Codice_Comune   548685 non-null  str
 1   Tipo_Dato       548685 non-null  str
 2   RESULT          548685 non-null  str
 3   Anno            548685 non-null  int64
 4   N. incidenti    548685 non-null  int64
 5   Nome_Comune     548613 non-null  str
 6   Popolazione     548685 non-null  int64
 7   Superficie_Kmq  548685 non-null  float64
dtypes: float64(1), int64(3), str(4)
memory usage: 33.5 MB

In [12]:
df_pivot = df_merged.pivot_table(
    index=['Codice_Comune', 'Nome_Comune', 'Popolazione', 'Superficie_Kmq', 'Anno'],
    columns='RESULT',
    values='N. incidenti',
    aggfunc='sum'
).reset_index()

In [13]:
df_pivot = df_pivot.rename(columns={
    '9': 'Totale_Incidenti',
    'F': 'Feriti',
    'M': 'Morti'
})

In [14]:
display(df_pivot.head())

RESULT,Codice_Comune,Nome_Comune,Popolazione,Superficie_Kmq,Anno,Totale_Incidenti,Feriti,Morti
0,001001,Agliè,2545,13.1462,2001,5,10,0
1,001001,Agliè,2545,13.1462,2002,5,10,0
2,001001,Agliè,2545,13.1462,2003,4,7,0
3,001001,Agliè,2545,13.1462,2004,9,13,0
4,001001,Agliè,2545,13.1462,2005,2,2,0

In [15]:
# Qua ho voluto eseguire un filtro temporale per selezionare solo gli anni che mi interessavano.
# Le giustificazioni sono: ----------------
anni_recenti = [2019, 2020, 2021, 2022, 2023]
df_finale = pd.DataFrame()
for anno in anni_recenti:
    df_temp = df_pivot[df_pivot['Anno'] == anno]
    df_finale = pd.concat([df_finale, df_temp])

df_finale.index = pd.RangeIndex(len(df_finale.index))
df_finale = df_finale.dropna().copy()

display(df_finale.head())

RESULT,Codice_Comune,Nome_Comune,Popolazione,Superficie_Kmq,Anno,Totale_Incidenti,Feriti,Morti
0,001001,Agliè,2545,13.1462,2019,3,5,0
1,001002,Airasca,3633,15.7393,2019,6,12,0
2,001003,Ala di Stura,459,46.3315,2019,0,0,0
3,001004,Albiano d'Ivrea,1638,11.7314,2019,3,3,1
4,001006,Almese,6355,17.8756,2019,4,7,0

In [16]:
# Ho voluto anche se non ancora del tutto puliiti, esportare questi dati con il filtro temporale per
# fare alcune verifiche di controllo. (scommentare per eseguire)
# percorso_export = "../../01_Data/Clean_Data/istat_filtrato_2019_2023.csv"
# df_finale.to_csv(percorso_export, index=False)

In [17]:
df_finale['Tasso_Incidenti_10k'] = (df_finale['Totale_Incidenti'] / df_finale['Popolazione']) * 10000
df_finale['Densita_Incidenti_Kmq'] = df_finale['Totale_Incidenti'] / df_finale['Superficie_Kmq']

df_finale['Tasso_Incidenti_10k'] = df_finale['Tasso_Incidenti_10k'].round(2)
df_finale['Densita_Incidenti_Kmq'] = df_finale['Densita_Incidenti_Kmq'].round(2)

display(df_finale.head())

RESULT,Codice_Comune,Nome_Comune,Popolazione,Superficie_Kmq,Anno,Totale_Incidenti,Feriti,Morti,Tasso_Incidenti_10k,Densita_Incidenti_Kmq
0,001001,Agliè,2545,13.1462,2019,3,5,0,11.79,0.23
1,001002,Airasca,3633,15.7393,2019,6,12,0,16.52,0.38
2,001003,Ala di Stura,459,46.3315,2019,0,0,0,0.00,0.00
3,001004,Albiano d'Ivrea,1638,11.7314,2019,3,3,1,18.32,0.26
4,001006,Almese,6355,17.8756,2019,4,7,0,6.29,0.22

In [19]:
# Qua ho deciso di aggiungere a posteriori una nuova colonna dove indica l'indice di fatalità,
# dopo durante l'analisi EDA mi è venuto in mente di aggiungere un nuovo indice di valutazione.
# Quindi ho dovuto calcolare l'indice di gravità in percentuale (% di incidenti con morti sul totale).

df_finale['Indice_Gravita_Perc'] = (df_finale['Morti'] / df_finale['Totale_Incidenti']) * 100

# Per i comuni con 0 incidenti il valore era NaN ma per il fare il calcolo giusto, i valori nan
# non ci devono essere, quindi li ho trasformati in 0.
df_finale['Indice_Gravita_Perc'] = df_finale['Indice_Gravita_Perc'].fillna(0)

# Qua ho voluto arrotondare a 2 decimali.
df_finale['Indice_Gravita_Perc'] = df_finale['Indice_Gravita_Perc'].round(2)

# Volevo verificare facendo una display.
display(df_finale.head(50))

RESULT,Codice_Comune,Nome_Comune,Popolazione,Superficie_Kmq,Anno,Totale_Incidenti,Feriti,Morti,Tasso_Incidenti_10k,Densita_Incidenti_Kmq,Indice_Gravita_Perc
0,001001,Agliè,2545,13.1462,2019,3,5,0,11.79,0.23,0.00
1,001002,Airasca,3633,15.7393,2019,6,12,0,16.52,0.38,0.00
2,001003,Ala di Stura,459,46.3315,2019,0,0,0,0.00,0.00,0.00
3,001004,Albiano d'Ivrea,1638,11.7314,2019,3,3,1,18.32,0.26,33.33
4,001006,Almese,6355,17.8756,2019,4,7,0,6.29,0.22,0.00
5,001007,Alpette,235,5.6261,2019,0,0,0,0.00,0.00,0.00
6,001008,Alpignano,16484,11.9193,2019,22,29,1,13.35,1.85,4.55
7,001009,Andezeno,2013,7.4860,2019,1,4,0,4.97,0.13,0.00
8,001010,Andrate,488,9.3085,2019,0,0,0,0.00,0.00,0.00
9,001011,Angrogna,838,38.8782,2019,0,0,0,0.00,0.00,0.00
10,001012,Arignano,1080,8.1668,2019,1,2,0,9.26,0.12,0.00
11,001013,Avigliana,12351,23.2172,2019,27,36,0,21.86,1.16,0.00
12,001014,Azeglio,1235,9.9605,2019,3,3,0,24.29,0.30,0.00
13,001015,Bairo,787,7.0859,2019,3,5,0,38.12,0.42,0.00
14,001016,Balangero,3064,13.0063,2019,3,3,0,9.79,0.23,0.00
15,001017,Baldissero Canavese,533,4.5064,2019,1,4,0,18.76,0.22,0.00
16,001018,Baldissero Torinese,3671,15.4054,2019,2,2,0,5.45,0.13,0.00
17,001019,Balme,110,62.7105,2019,0,0,0,0.00,0.00,0.00
18,001020,Banchette,3112,2.0289,2019,4,7,1,12.85,1.97,25.00
19,001021,Barbania,1585,12.8027,2019,0,0,0,0.00,0.00,0.00
20,001022,Bardonecchia,3078,132.2030,2019,4,5,1,13.00,0.03,25.00
21,001023,Barone Canavese,559,3.9864,2019,4,5,0,71.56,1.00,0.00
22,001024,Beinasco,17532,6.7343,2019,43,64,0,24.53,6.39,0.00
23,001025,Bibiana,3392,18.5979,2019,2,2,0,5.90,0.11,0.00
24,001026,Bobbio Pellice,537,94.0819,2019,0,0,0,0.00,0.00,0.00
25,001027,Bollengo,2097,14.2234,2019,3,5,0,14.31,0.21,0.00
26,001028,Borgaro Torinese,11773,11.1039,2019,11,11,0,9.34,0.99,0.00
27,001029,Borgiallo,592,6.9648,2019,0,0,0,0.00,0.00,0.00
28,001030,Borgofranco d'Ivrea,3590,13.4189,2019,5,7,0,13.93,0.37,0.00
29,001031,Borgomasino,772,12.3712,2019,0,0,0,0.00,0.00,0.00
30,001032,Borgone Susa,2187,4.9617,2019,6,9,0,27.43,1.21,0.00
31,001033,Bosconero,3074,10.9190,2019,2,2,0,6.51,0.18,0.00
32,001034,Brandizzo,8798,6.2914,2019,10,13,0,11.37,1.59,0.00
33,001035,Bricherasio,4564,22.7585,2019,4,14,0,8.76,0.18,0.00
34,001036,Brosso,402,11.1350,2019,0,0,0,0.00,0.00,0.00
35,001037,Brozolo,449,8.9504,2019,1,2,0,22.27,0.11,0.00
36,001038,Bruino,8475,5.5701,2019,5,7,0,5.90,0.90,0.00
37,001039,Brusasco,1482,14.3592,2019,2,2,0,13.50,0.14,0.00
38,001040,Bruzolo,1487,12.5598,2019,4,6,0,26.90,0.32,0.00
39,001041,Buriasco,1329,14.6868,2019,3,6,1,22.57,0.20,33.33
40,001042,Burolo,1134,5.4760,2019,1,2,0,8.82,0.18,0.00
41,001043,Busano,1622,5.0591,2019,6,10,0,36.99,1.19,0.00
42,001044,Bussoleno,5703,37.0661,2019,17,31,0,29.81,0.46,0.00
43,001045,Buttigliera Alta,6292,8.0973,2019,2,3,0,3.18,0.25,0.00
44,001046,Cafasse,3334,10.2312,2019,6,12,0,18.00,0.59,0.00
45,001047,Caluso,7344,39.4925,2019,12,28,0,16.34,0.30,0.00
46,001048,Cambiano,5915,14.1314,2019,6,18,0,10.14,0.42,0.00
47,001049,Campiglione Fenile,1333,11.0863,2019,1,1,0,7.50,0.09,0.00
48,001050,Candia Canavese,1219,9.1318,2019,0,0,0,0.00,0.00,0.00
49,001051,Candiolo,5627,11.8499,2019,10,15,0,17.77,0.84,0.00

In [20]:
percorso_export_finale = "../../01_Data/Clean_Data/istat_incidenti_pulito_2019_2023.csv"
df_finale.to_csv(percorso_export_finale, index=False)