In [13]:
# Commento

In [14]:
import pandas as pd
percorso_istat = "../../01_Data/Raw_Data/istat_incidenti_raw.csv"
percorso_situas = "../../01_Data/Raw_Data/Comuni - Dimensione Data Indagine 31-12-2020 Stampa 21062026185720.csv"

In [17]:
#
df_istat = pd.read_csv(percorso_istat, dtype={'REF_AREA': str})
df_situas = pd.read_csv(percorso_situas, sep=';', dtype={'Codice Comune (alfanumerico)': str})

In [16]:
display(df_istat.head(3))

print("\n--------------------------------------------------\n")

display(df_situas.head(3))

,DATAFLOW,FREQ,REF_AREA,DATA_TYPE,RESULT,TIME_PERIOD,OBS_VALUE,OBS_STATUS,NOTE_DS,NOTE_REF_AREA,NOTE_DATA_TYPE,NOTE_RESULT,NOTE_TIME_PERIOD,BASE_PER,UNIT_MEAS,UNIT_MULT
0,IT1:41_983(1.0),A,001001,KILLINJ,F,2001,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IT1:41_983(1.0),A,001001,KILLINJ,F,2002,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IT1:41_983(1.0),A,001001,KILLINJ,F,2003,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--------------------------------------------------

,Codice Ripartizione geografica,Codice Regione,Codice Provincia (Storico),Codice Provincia/Uts,Codice Comune (alfanumerico),Codice Comune (numerico),Comune,Comune (dizione straniera),Sigla automobilistica,Capoluogo di Provincia/Uts,Capoluogo di Regione,Popolazione legale,Anno Censimento,Superficie (Kmq),Anno (Superficie),Popolazione residente,Anno (Popolazione residente)
0,1,1,1,201,001001,1001,Agliè,NaN,TO,0,0,2644,2011,"13,1462",2020,2545,2020
1,1,1,1,201,001002,1002,Airasca,NaN,TO,0,0,3819,2011,"15,7393",2020,3633,2020
2,1,1,1,201,001003,1003,Ala di Stura,NaN,TO,0,0,462,2011,"46,3315",2020,459,2020

In [21]:
df_istat.info()

<class 'pandas.DataFrame'>
RangeIndex: 573552 entries, 0 to 573551
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   DATAFLOW          573552 non-null  str
 1   FREQ              573552 non-null  str
 2   REF_AREA          573552 non-null  str
 3   DATA_TYPE         573552 non-null  str
 4   RESULT            573552 non-null  str
 5   TIME_PERIOD       573552 non-null  int64
 6   OBS_VALUE         573552 non-null  int64
 7   OBS_STATUS        0 non-null       float64
 8   NOTE_DS           0 non-null       float64
 9   NOTE_REF_AREA     0 non-null       float64
 10  NOTE_DATA_TYPE    0 non-null       float64
 11  NOTE_RESULT       0 non-null       float64
 12  NOTE_TIME_PERIOD  0 non-null       float64
 13  BASE_PER          0 non-null       float64
 14  UNIT_MEAS         0 non-null       float64
 15  UNIT_MULT         0 non-null       float64
dtypes: float64(9), int64(2), str(5)
memory usage: 70.0 MB

In [22]:
df_situas.info()

<class 'pandas.DataFrame'>
RangeIndex: 7903 entries, 0 to 7902
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Codice Ripartizione geografica  7903 non-null   int64
 1   Codice Regione                  7903 non-null   int64
 2   Codice Provincia (Storico)      7903 non-null   int64
 3   Codice Provincia/Uts            7903 non-null   int64
 4   Codice Comune (alfanumerico)    7903 non-null   str
 5   Codice Comune (numerico)        7903 non-null   int64
 6   Comune                          7902 non-null   str
 7   Comune (dizione straniera)      124 non-null    str
 8   Sigla automobilistica           7811 non-null   str
 9   Capoluogo di Provincia/Uts      7903 non-null   int64
 10  Capoluogo di Regione            7903 non-null   int64
 11  Popolazione legale              7903 non-null   int64
 12  Anno Censimento                 7903 non-null   int64
 13  Superficie (Kmq)                7903 non-null   str
 14  Anno (Superficie)               7903 non-null   int64
 15  Popolazione residente           7903 non-null   int64
 16  Anno (Popolazione residente)    7903 non-null   int64
dtypes: int64(12), str(5)
memory usage: 1.0 MB

In [18]:
colonne_utili_istat = ['DATAFLOW', 'FREQ', 'REF_AREA', 'DATA_TYPE', 'RESULT', 'TIME_PERIOD', 'OBS_VALUE']

df_istat_clean = df_istat[colonne_utili_istat]

df_istat_clean = df_istat_clean.rename(columns={
    'REF_AREA': 'Codice_Comune',
    'DATA_TYPE': 'Tipo_Dato',
    'TIME_PERIOD': 'Anno',
    'OBS_VALUE': 'Valore'
})

display(df_istat_clean.head(3))

          DATAFLOW FREQ Codice_Comune Tipo_Dato RESULT  Anno  Valore
0  IT1:41_983(1.0)    A        001001   KILLINJ      F  2001      10
1  IT1:41_983(1.0)    A        001001   KILLINJ      F  2002      10
2  IT1:41_983(1.0)    A        001001   KILLINJ      F  2003       7

In [24]:
df_situas['Superficie (Kmq)'] = df_situas['Superficie (Kmq)'].str.replace('.', '', regex=False).str.replace(',', '.', regex=False).astype(float)

colonne_utili_situas = [
    'Codice Comune (alfanumerico)', 
    'Comune', 
    'Popolazione residente', 
    'Superficie (Kmq)'
]
df_situas_clean = df_situas[colonne_utili_situas]

df_situas_clean = df_situas_clean.rename(columns={
    'Codice Comune (alfanumerico)': 'Codice_Comune',
    'Comune': 'Nome_Comune',
    'Popolazione residente': 'Popolazione',
    'Superficie (Kmq)': 'Superficie_Kmq'
})

display(df_situas_clean.head(3))

  Codice_Comune   Nome_Comune  Popolazione  Superficie_Kmq
0        001001         Agliè         2545         13.1462
1        001002       Airasca         3633         15.7393
2        001003  Ala di Stura          459         46.3315